project:
  type: website
  output-dir: docs

website:
  site-url: "https://ds100.org/debugging-guide/"
  page-footer: 
    center:
      - text: Accessibility
        href: "https://dap.berkeley.edu/get-help/report-web-accessibility-issue"
      - text: Nondiscrimination
        href: "https://ophd.berkeley.edu/policies-and-procedures/nondiscrimination-policy-statement"
  favicon: data100_logo.png
  title: "Data 100 Debugging Guide"
  image: data100_logo.png
  repo-url: https://github.com/DS-100/debugging-guide
  search:
    location: sidebar
    type: textbox
  sidebar:
    logo: "data100_logo.png"
    style: "docked"
    title: "Data 100 Debugging Guide"
    logo-alt: "Data 100 logo"
    tools:
      - icon: github
        href: https://github.com/DS-100/debugging-guide
    contents:
      - index.md
      - jupyter101/jupyter101.md
      - jupyter_datahub/jupyter_datahub.md
      - autograder_gradescope/autograder_gradescope.md
      - pandas/pandas.md
      - regex/regex.md
      - visualizations/visualizations.md
      - projA1/projA1.md
      - projA2/projA2.md
      - sql/sql.md
format:
  html:
    theme: cosmos
    toc: true
    toc-depth: 5
    toc-expand: 3 # depth to expand index
    callout-icon: false
    number-sections: false
    include-after-body: 
      - a11y-fixes.html
