project:
  type: website
  output-dir: docs

book:
  site-url: "https://ds100.org/debugging-guide/"
  favicon: data100_logo.png
  title: "Data 100 Debugging Guide"
  image: data100_logo.png
  author: ["Yash Dave", "Lillian Weng", "Wesley Zheng", "Emrie Loh"]
  repo-url: https://github.com/DS-100/debugging-guide
  search:
    location: sidebar
    type: textbox
  chapters:
    - index.md
    - jupyter101/jupyter101.md
    - jupyter_datahub/jupyter_datahub.md
    - autograder_gradescope/autograder_gradescope.md
    - pandas/pandas.md
    - regex/regex.md
    - visualizations/visualizations.md
    - projA1/projA1.md
    - projA2/projA2.md
    - sql/sql.md

  sidebar:
    logo: "data100_logo.png"
format:
  html:
    theme: cosmos
    toc: true
    toc-depth: 5
    toc-expand: 3 # depth to expand index
    callout-icon: false
    number-sections: false
    include-after-body: 
      - a11y-fixes.html
  pdf: default
